config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :tickets

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  root :to => "tickets#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_accessor :remember_token

  before_save { email.downcase! }

  validates :name, length: {minimum: 3, maximum: 50}, presence: true
  validates :last_name, length: {minimum: 3, maximum: 50}, presence: true
  validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: true
  validates :age, :numericality => {:greater_than => 0, :less_than_or_equal_to => 100}, presence: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  has_many :tickets

  class << self
    # Returns the hash digest of the given string.
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
          BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # Returns a random token.
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create

    @user = User.new(users_params)
    if @user.save
      log_in @user
      flash[:komunikat] = 'Zarejestrowałeś się poprawnie!'
      redirect_to @user
    else
      render :action => "new"
    end

  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end


  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def users_params
    params.require(:user).permit(:name, :last_name, :email, :age, :password, :password_confirmation, :tickets_number)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Cześć! @user.name</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
      <li>
        <%= link_to user.email, user %>
        <%= user.name %>
        <%= user.last_name %>
        <% if current_user.admin? && !current_user?(user) %>
            | <%= link_to "delete", user, method: :delete,
                          data: { confirm: "You sure?" } %>
        <% end %>
      </li>

  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.text_field :age %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, "Password confirmation" %><br>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="actions">
      <%= f.submit "Create my account", class: "btn btn-primary"%>
    </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
       Email: <%= @user.email %><br>
        Imię: <%= @user.name %> <br>
        Nazwisko: <%= @user.last_name%><br>
        Wiek: <%= @user.age%>
      </h1>
    </section>
  </aside>
</div>


<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <nav>
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
            <li><%= link_to "Events", events_path %></li>
            <li><%= link_to "Tickets", tickets_path%></li>
            <li><%= link_to "Users", users_path %></li>

              <% if current_user?(@user) %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                  </ul>
                </li>
              <% end %>


        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>

</header>