config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :tickets

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  root :to => "tickets#index"

end

app/models/event.rb
# require 'validators/future_validator.rb'

class Event < ActiveRecord::Base


  validates :artist, presence: true
  validates :description, length: {maximum: 200}, presence: true
  validates :price_low, presence: true
  validates :price_high, presence: true
  validates :event_date, future: true, presence: true


  has_many :tickets

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create

    @event = Event.new(event_params)
    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      redirect_to events_path
    else
      render :action => "new"
    end
  end

  def edit
  end

# PATCH/PUT /events/1
# PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /tickets/1
# DELETE /tickets/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date, :for_adults, :seats_number)
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% @event.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :artist %><br>
      <%= f.text_field :artist %>
    </div>
    <div class="field">
      <%= f.label :desctiption %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :price_low %><br>
      <%= f.text_field :price_low %>
    </div>
    <div class="field">
      <%= f.label :price_high %><br>
      <%= f.text_field :price_high %>
    </div>
    <div class="field">
      <%= f.label :event_date %><br>
      <%= f.date_field :event_date %>
    </div>
    <div class="field">
      <%= f.label :seats_number %><br>
      <%= f.text_field :seats_number %>
    </div>
    <div class="field">
      <%= f.label :for_adults %><br>
      <%= f.check_box :for_adults %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path%>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<% if logged_in? %>
    <%= link_to 'Back', current_user%>
<% else %>
    <%= link_to 'Back', root_path%>
<% end %>



<table>
  <thead>
  <tr>
    <th>Artist</th>
    <th>Description</th>
    <th>Prices</th>
    <th>Event date</th>
    <th>Sold Tickets count</th>
    <th>Seats count</th>
    <th>For adults?</th>
    <th colspan="4"></th>
  </tr>
  </thead>

  <tbody>
  <% @events.each do |event| %>
      <tr>
        <td><%= event.artist %></td>
        <td><%= event.description %></td>
        <td><%= event.price_low %> - <%= event.price_high %></td>
        <td><%= event.event_date %></td>
        <td><%= event.tickets.count %></td>
        <td><%= event.seats_number %></td>
        <td><%= event.for_adults %></td>
        <td><%= link_to 'Show', event %></td>
        <% if logged_in? && current_user.admin? %>
            <td><%= link_to 'Edit', edit_event_path(event) %></td>
            <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
  <% end %>
  </tbody>
</table>

<% if logged_in? && current_user.admin? %>
    <%= link_to 'New Event', new_event_path %>
<% end %>


<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @event.event_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Prices:</strong>
  <%= @event.price_low %> - <%= @event.price_high %>
</p>

<p>
  <strong>Seats count:</strong>
  <%= @event.seats_number %>
</p>

<p>
  <strong>For adults?:</strong>
  <%= @event.for_adults %>
</p>

<% if logged_in? && current_user.admin? %>
    <%= link_to 'Edit', edit_event_path(@event) %> |
<% end %>

<%= link_to 'Back', events_path %>