config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :tickets

  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  root :to => "tickets#index"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, length: {minimum: 6}, presence: true
  validates :email_address, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :price, presence: true
  validates :seat_id_seq, length: {minimum: 2, maximum: 4}, presence: true
  validates :phone, length: { is: 9 }, presence: true
  validates :age, :numericality => { :greater_than => 0, :less_than_or_equal_to => 100 }, presence: true
  validates :tickets_number, :numericality => { :greater_than => 0, :less_than_or_equal_to => 6 }

  belongs_to :event
  belongs_to :user

  SEATS = ['A12','A13', 'A14' , 'B12', 'B13' ,'B14', 'C12','C13' , 'C14' , 'D12' , 'D13'  ,  'D14' ]
  NOT_TAKEN_SEATS = ['A12','A13', 'A14' , 'B12', 'B13' ,'B14', 'C12','C13' , 'C14' , 'D12' , 'D13'  ,  'D14' ]
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    if current_user.admin?
      @tickets = Ticket.all
    else
      @tickets = Ticket.where(user_id: current_user.id)
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])
    @event = Event.where(id: @ticket.event_id).take
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket.name = current_user.name + ' ' + current_user.last_name
    @ticket.age = current_user.age
    @ticket.email_address = current_user.email
    @events = Event.all
  end

  # GET /tickets/1/edit
  def edit
    @events = Event.all

  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id
    respond_to do |format|
      puts(@ticket.event_id)
      if more_than_six_tickets?(@ticket.event_id, current_user.id, @ticket.tickets_number)
        format.html { redirect_to new_ticket_url, :alert => "Nie możesz kupić więcej niż 5 biletów na to wydarzenie! Masz już #{@current_sum} biletów" }
        format.json { head :ok }
      elsif is_under_adult_age?(current_user.age, @ticket.event_id)
        format.html { redirect_to new_ticket_url, :alert => 'Event tylko dla dorosłych!!! Masz mniej niż 18 lat' }
        format.json { head :ok }
      else

        if @ticket.save
          format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        else
          format.html { render :new }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end

    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|

      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end

    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :age, :tickets_number, :event_id, :user_id)
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper


  def more_than_six_tickets?(event_id, user_id, ticket_number)
    count = Ticket.where(user_id: user_id).where(event_id: event_id).sum('tickets_number')
    @current_sum = count
    count + ticket_number >= 6

  end

  def check_if_seat_taken(event_id)
   not_taken_seats = Ticket::SEATS
    Ticket::SEATS.each { |seat|
      ticket = Ticket.where(seat_id_seq: seat).where(event_id: event_id).take
      if !ticket.nil?
        not_taken_seats = not_taken_seats.delete(seat)
      end
    }

   not_taken_seats

  end


  def is_under_adult_age?(user_age, event_id)

    event = Event.where(id: event_id).take
    if event.for_adults
      return user_age < 18
    else
      return false
    end


  end

end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
    <% if @ticket.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

          <ul>
            <% @ticket.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :event_id %><br>
      <%= f.collection_select :event_id, Event.all, :id, :artist,  { :prompt => true} %>
    </div>

    <div class="field">
      <%= f.label :seat_id_seq %><br>
      <%= f.select :seat_id_seq, Ticket::SEATS, { :prompt => true } %>
    </div>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_area :address %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    <div class="field">
      <%= f.label :email_address %><br>
      <%= f.text_field :email_address %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :phone %>
    </div>
    <div class="field">
      <%= f.label :age %><br>
      <%= f.text_field :age %>
    </div>
    <div class="field">
      <%= f.label :tickets_number %><br>
      <%= f.text_field :tickets_number %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<%= link_to 'Back', current_user%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th>Age</th>
      <th>  Number of <br>bought tickets  </th>
      <th>Event name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= ticket.age %></td>
        <td><%= ticket.tickets_number %></td>
        <td><%= Event.where(id: ticket.event_id).select(:artist).map(&:artist) %></td>


        <td><%= link_to 'Show', ticket %></td>
        <% if current_user.admin? %>
            <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
            <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seat id seq:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

<p>
  <strong>Age:</strong>
  <%= @ticket.age %>
</p>

<p>
  <strong>Bought tickets:</strong>
  <%= @ticket.tickets_number %>
</p>

<p>
  <strong>Event name:</strong>
  <%= @event.artist %>
</p>

<p>
  <strong>User id:</strong>
  <%= @ticket.user_id %>
</p>

<% if current_user.admin? %>
    <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<% end %>


<%= link_to 'Back', tickets_path %>